/**
 * API Routes for Teacher Management
 *
 * This module handles HTTP requests for teacher-related operations:
 * - GET /api/teachers: Retrieve all teachers
 * - POST /api/teachers: Create a new teacher
 */

import { NextRequest, NextResponse } from 'next/server';
import { executeQuery } from '@/lib/oracle';
import oracledb from 'oracledb';

/**
 * Teacher type definition matching database schema
 */
interface Teacher {
  MAGV: string;
  HOTEN: string;
  NGAYSINH?: Date;
  GIOITINH?: number;
  QUEQUAN?: string;
  DIACHI?: string;
  SDT?: number;
  EMAIL: string;
  MABM?: string;
}

/**
 * GET /api/teachers
 * Retrieve all teachers from the database
 *
 * @returns JSON array of teachers
 */
export async function GET() {
  try {
    // Query to fetch all teachers from the database
    // Direct select from NVARCHAR2 columns - oracledb will handle UTF-8 conversion
    const result = await executeQuery<Teacher>(
      `SELECT
        TRIM(MAGV) as MAGV,
        HOTEN,
        NGAYSINH,
        GIOITINH,
        QUEQUAN,
        DIACHI,
        SDT,
        EMAIL,
        TRIM(MABM) as MABM
      FROM GIAOVIEN
      ORDER BY MAGV`,
      {},
      {
        outFormat: oracledb.OUT_FORMAT_OBJECT,
        fetchInfo: {
          "HOTEN": { type: oracledb.STRING },
          "QUEQUAN": { type: oracledb.STRING },
          "DIACHI": { type: oracledb.STRING },
          "EMAIL": { type: oracledb.STRING }
        }
      }
    );

    // Transform database field names to camelCase for JSON response
    const teachers = (result.rows || []).map((teacher) => ({
      maGV: teacher.MAGV?.trim(),
      hoTen: teacher.HOTEN || '',
      ngaySinh: teacher.NGAYSINH || null,
      gioiTinh: teacher.GIOITINH || null,
      queQuan: teacher.QUEQUAN || '',
      diaChi: teacher.DIACHI || '',
      sdt: teacher.SDT || null,
      email: teacher.EMAIL || '',
      maBM: teacher.MABM?.trim() || '',
    }));

    return NextResponse.json(teachers, { status: 200 });
  } catch (error) {
    console.error('Error fetching teachers:', error);

    return NextResponse.json(
      {
        error: 'Failed to fetch teachers',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/teachers
 * Create a new teacher in the database
 *
 * @param request - Next.js request object containing teacher data
 * @returns JSON response with created teacher ID
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body = await request.json();
    const { hoTen, ngaySinh, gioiTinh, queQuan, diaChi, sdt, email, maBM } = body;

    // Validate required fields
    if (!hoTen) {
      return NextResponse.json(
        { error: 'Thiếu thông tin bắt buộc: hoTen là bắt buộc' },
        { status: 400 }
      );
    }

    // Validate email format if provided
    if (email) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        return NextResponse.json(
          { error: 'Định dạng email không hợp lệ' },
          { status: 400 }
        );
      }
    }

    // Insert new teacher into database (MAGV will be auto-generated by trigger)
    // Use DB_TYPE_NVARCHAR for Vietnamese text fields to ensure proper encoding
    const result = await executeQuery(
      `INSERT INTO GIAOVIEN (HOTEN, NGAYSINH, GIOITINH, QUEQUAN, DIACHI, SDT, EMAIL, MABM)
       VALUES (:hoTen, TO_DATE(:ngaySinh, 'YYYY-MM-DD'), :gioiTinh, :queQuan, :diaChi, :sdt, :email, :maBM)`,
      {
        hoTen: { val: hoTen, type: oracledb.DB_TYPE_NVARCHAR },
        ngaySinh: ngaySinh || null,
        gioiTinh: gioiTinh || null,
        queQuan: { val: queQuan || null, type: oracledb.DB_TYPE_NVARCHAR },
        diaChi: { val: diaChi || null, type: oracledb.DB_TYPE_NVARCHAR },
        sdt: sdt || null,
        email: { val: email || null, type: oracledb.DB_TYPE_NVARCHAR },
        maBM: { val: maBM || null, type: oracledb.STRING }
      }
    );

    // Get the auto-generated MAGV
    const newTeacher = await executeQuery<{ MAGV: string }>(
      `SELECT MAGV FROM GIAOVIEN WHERE ROWID = (SELECT MAX(ROWID) FROM GIAOVIEN)`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    const generatedMaGV = newTeacher.rows?.[0]?.MAGV?.trim() || null;

    return NextResponse.json(
      {
        message: 'Tạo giáo viên thành công',
        maGV: generatedMaGV,
        rowsAffected: result.rowsAffected
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error creating teacher:', error);

    // Check for unique constraint violation
    if (error instanceof Error && error.message.includes('ORA-00001')) {
      return NextResponse.json(
        { error: 'Mã giáo viên đã tồn tại' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      {
        error: 'Không thể tạo giáo viên',
        message: error instanceof Error ? error.message : 'Lỗi không xác định'
      },
      { status: 500 }
    );
  }
}
