-- Create sequence for KHOA table
CREATE SEQUENCE SEQ_KHOA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create trigger to auto-generate MAKHOA
CREATE OR REPLACE TRIGGER TRG_KHOA_MAKHOA
    BEFORE INSERT ON KHOA
    FOR EACH ROW
BEGIN
    IF :NEW.MAKHOA IS NULL THEN
        SELECT 'KH' || LPAD(SEQ_KHOA.NEXTVAL, 3, '0') INTO :NEW.MAKHOA FROM DUAL;
    END IF;
END;
/

-- Grant permissions
GRANT SELECT ON SEQ_KHOA TO PUBLIC;
