/**
 * API Routes for Department Management (Quản lý Bộ môn)
 *
 * GET /api/departments: Retrieve all departments
 * POST /api/departments: Create a new department
 */

import { NextRequest, NextResponse } from 'next/server';
import { executeQuery } from '@/lib/oracle';
import oracledb from 'oracledb';

interface Department {
  MABM: string;
  TENBM: string;
  DIACHI?: string;
  MAKHOA?: string;
  MACHUNHIEMBM?: string;
}

/**
 * GET /api/departments
 */
export async function GET() {
  try {
    const result = await executeQuery<Department>(
      `SELECT
        BM.MABM,
        BM.TENBM,
        BM.DIACHI,
        BM.MAKHOA,
        BM.MACHUNHIEMBM,
        K.TENKHOA,
        GV.HOTEN as TENCHUNHIEM
      FROM BOMON BM
      LEFT JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
      LEFT JOIN GIAOVIEN GV ON BM.MACHUNHIEMBM = GV.MAGV
      ORDER BY BM.MABM`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    const departments = (result.rows || []).map((dept: any) => ({
      maBM: dept.MABM?.trim(),
      tenBM: dept.TENBM || '',
      diaChi: dept.DIACHI || '',
      maKhoa: dept.MAKHOA?.trim() || '',
      tenKhoa: dept.TENKHOA || '',
      maChuNhiemBM: dept.MACHUNHIEMBM?.trim() || '',
      tenChuNhiem: dept.TENCHUNHIEM || ''
    }));

    return NextResponse.json(departments, { status: 200 });
  } catch (error) {
    console.error('Error fetching departments:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch departments',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/departments
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { TENBM, DIACHI, MAKHOA, MACHUNHIEMBM } = body;

    if (!TENBM) {
      return NextResponse.json(
        { error: 'Thiếu thông tin bắt buộc: TENBM là bắt buộc' },
        { status: 400 }
      );
    }

    // Insert new department (MABM will be auto-generated by trigger)
    // Use DB_TYPE_NVARCHAR for Vietnamese text fields to ensure proper encoding
    const result = await executeQuery(
      `INSERT INTO BOMON (TENBM, DIACHI, MAKHOA, MACHUNHIEMBM)
       VALUES (:tenBM, :diaChi, :maKhoa, :maChuNhiemBM)`,
      {
        tenBM: { val: TENBM, type: oracledb.DB_TYPE_NVARCHAR },
        diaChi: { val: DIACHI || null, type: oracledb.DB_TYPE_NVARCHAR },
        maKhoa: { val: MAKHOA || null, type: oracledb.STRING },
        maChuNhiemBM: { val: MACHUNHIEMBM || null, type: oracledb.STRING }
      }
    );

    const newDept = await executeQuery<{ MABM: string }>(
      `SELECT MABM FROM BOMON WHERE ROWID = (SELECT MAX(ROWID) FROM BOMON)`,
      {},
      { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );

    const generatedMaBM = newDept.rows?.[0]?.MABM?.trim() || null;

    return NextResponse.json(
      {
        message: 'Tạo bộ môn thành công',
        maBM: generatedMaBM,
        rowsAffected: result.rowsAffected
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Error creating department:', error);

    if (error instanceof Error && error.message.includes('ORA-00001')) {
      return NextResponse.json(
        { error: 'Mã bộ môn đã tồn tại' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      {
        error: 'Không thể tạo bộ môn',
        message: error instanceof Error ? error.message : 'Lỗi không xác định'
      },
      { status: 500 }
    );
  }
}
